public sealed class PiarPt1Response
{
    public Guid id { get; init; }
    public Guid id_uss { get; init; }
    public int est_piar { get; init; }
    public Guid id_est { get; init; }
    public Guid id_prof { get; init; }
    public DateTime fec_dil { get; init; }
    public string? nom_dil { get; init; }
    public string? rol_se_ie { get; init; }
    public string? nom_est { get; init; }
    public string? ape_est { get; init; }
    public string? lug_nac_est { get; init; }
    public int edad_est { get; init; }
    public DateTime fec_nac_est { get; init; }
    public string? tip_doc_est { get; init; }
    public string? otro_doc_est { get; init; }
    public string? doc_est { get; init; }
    public string? depa_est { get; init; }
    public string? mun_est { get; init; }
    public string? dir_est { get; init; }
    public string? barrio_est { get; init; }
    public string? tel_est { get; init; }
    public string? ema_est { get; init; }
    public bool cen_pro { get; init; }
    public string? lugar_cen_pro { get; init; }
    public string? grd_asp_est { get; init; }
    public string? grp_etn { get; init; }
    public bool vic_conf { get; init; }
    public bool reg_vic_conf { get; init; }
    public bool afili_salud { get; init; }
    public string? eps { get; init; }
    public string? contr_subsi { get; init; }
    public string? lug_emer { get; init; }
    public bool aten_salud { get; init; }
    public string? frec_aten_salud { get; init; }
    public bool diag_med { get; init; }
    public string? cual_diag_med { get; init; }
    public bool ter_med { get; init; }
    public string? cual_ter_med { get; init; }
    public bool trat_med { get; init; }
    public string? cual_trat_med { get; init; }
    public bool cons_meds { get; init; }
    public string? meds_frecuencia { get; init; }
    public bool prods_mov { get; init; }
    public string? cual_prods_mov { get; init; }
    public string? nom_mam { get; init; }
    public string? ocu_mam { get; init; }
    public string? niv_ed_mam { get; init; }
    public string? nom_pap { get; init; }
    public string? ocu_pap { get; init; }
    public string? niv_ed_pap { get; init; }
    public string? nom_cui { get; init; }
    public string? par_cui { get; init; }
    public string? niv_ed_cui { get; init; }
    public string? tel_cui { get; init; }
    public string? ema_cui { get; init; }
    public int num_her { get; init; }
    public int lug_ocu_est { get; init; }
    public string? per_viv_e { get; init; }
    public string? apo_cri_e { get; init; }
    public bool baj_prot { get; init; }
    public bool sub_inst_ent { get; init; }
    public string? tip_sub { get; init; }
    public bool vinc_otr_inst { get; init; }
    public string? cual_inst { get; init; }
    public string? no_inst { get; init; }
    public string? ult_grad { get; init; }
    public bool aprov_ult_grad { get; init; }
    public string? obs_ult_grd { get; init; }
    public bool infm_ped { get; init; }
    public string? inst_infm { get; init; }
    public bool prog_comp { get; init; }
    public string? tipo_prog_comp { get; init; }
    public string? nom_inst { get; init; }
    public string? sed_inst { get; init; }
    public string? trans_inst { get; init; }
    public string? dist_inst { get; init; }

}