namespace PiarServer.Application.Piars.GetPiar;

public sealed class PiarResponse
{
    public Guid Id {get; init;}
    public Guid IdUss {get; init;}
    public int EstPiar {get; init;}
    public Guid IdEst {get; init;}
    public Guid IdProf {get; init;}
    public DateTime FecDil {get; init;}
    public string? NomDil {get; init;}
    public string? RolSeIe {get; init;}
    public string? NomEst {get; init;}
    public string? ApeEst {get; init;}
    public string? LugNacEst {get; init;}
    public int EdadEst {get; init;}
    public DateTime FecNacEst {get; init;}
    public string? TipDocEst {get; init;}
    public string? OtroDocEst {get; init;}
    public string? DocEst {get; init;}
    public string? DepaEst {get; init;}
    public string? MunEst {get; init;}
    public string? DirEst {get; init;}
    public string? BarrioEst {get; init;}
    public string? TelEst {get; init;}
    public string? EmaEst {get; init;}
    public bool CenPro {get; init;}
    public string? LugarCenPro {get; init;}
    public string? GrdAspEst {get; init;}
    public string? GrpEtn {get; init;}
    public bool VicConf {get; init;}
    public bool RegVicConf {get; init;}
    public bool AfiliSalud {get; init;}
    public string? Eps {get; init;}
    public string? ContrSubsi {get; init;}
    public string? LugEmer {get; init;}
    public bool AtenSalud {get; init;}
    public string? FrecAtenSalud {get; init;}
    public bool DiagMed {get; init;}
    public string? CualDiagMed {get; init;}
    public bool TerMed {get; init;}
    public string? CualTerMed {get; init;}
    public bool TratMed {get; init;}
    public string? CualTratMed {get; init;}
    public bool ConsMeds {get; init;}
    public string? MedsFrecuencia {get; init;}
    public bool ProdsMov {get; init;}
    public string? CualProdsMov {get; init;}
    public string? NomMam {get; init;}
    public string? OcuMam {get; init;}
    public string? NivEdMam {get; init;}
    public string? NomPap {get; init;}
    public string? OcuPap {get; init;}
    public string? NivEdPap {get; init;}
    public string? NomCui {get; init;}
    public string? ParCui {get; init;}
    public string? NivEdCui {get; init;}
    public string? TelCui {get; init;}
    public string? EmaCui {get; init;}
    public int NumHer {get; init;}
    public int LugOcuEst {get; init;}
    public string? PerVivE {get; init;}
    public string? ApoCriE {get; init;}
    public bool BajProt {get; init;}
    public bool SubInstEnt {get; init;}
    public string? TipSub {get; init;}
    public bool VincOtrInst {get; init;}
    public string? CualInst {get; init;}
    public string? NoInst {get; init;}
    public string? UltGrado {get; init;}
    public bool AprovUltGrad {get; init;}
    public string? ObsUltGrd {get; init;}
    public bool InfmPed {get; init;}
    public string? InstInfm {get; init;}
    public bool ProgComp {get; init;}
    public string? TipoProgComp {get; init;}
    public string? NomInst {get; init;}
    public string? SedInst {get; init;}
    public string? TransInst {get; init;}
    public string? DistInst {get; init;}
    public string? InstEduA2 {get; init;}
    public string? SedA2 {get; init;}
    public string? JorA2 {get; init;}
    public string? DocsEla {get; init;}
    public string? CarsDog {get; init;}
    public string? Desc1Est {get; init;}
    public string? Desc2Est {get; init;}
    public string? AccFam {get; init;}
    public string? EstrFam {get; init;}
    public string? AccDoc {get; init;}
    public string? EstrDoc {get; init;}
    public string? AccDir {get; init;}
    public string? EstrDir {get; init;}
    public string? AccAdm {get; init;}
    public string? EstrAdm {get; init;}
    public string? AccPar {get; init;}
    public string? EstrPar {get; init;}
    public DateTime FecDilA3 {get; init;}
    public string? InstEduA30 {get; init;}
    public string? DocDir {get; init;}
    public string? NomFam {get; init;}
}